sudo: required

os: osx
osx_image: xcode8.3

cache:
  directories:
  - scripts/unity-installers/

before_install:
  - chmod a+x ./*.sh
  - chmod a+x ./scripts/*.sh
  - mkdir -p scripts/unity-installers/

install:
  # unity editor
  - cd scripts; ./install.sh editor; cd -
  
script:
  - ./export_package.sh
  - ls -al ./dist
  
after_script:
  - cat export.log

notifications:
  email: false

branches:
  only:
  - master